language: node_js
node_js:
  - '10'
dist: trusty
install: true
cache:
  yarn: true
env:
  - WEBSITE_CHANGED = git diff --name-only $TRAVIS_COMMIT_RANGE | grep -E "website/|docs/"
jobs:
  include:
    - name: "website:publish"
      if: type != pull_request AND branch = master
      script:
        - git config --global user.name "${GH_NAME}"
        - git config --global user.email "${GH_EMAIL}"
        - echo "machine github.com login ${GH_NAME} password ${GH_TOKEN}" > ~/.netrc
        - cd website && yarn install && GIT_USER="${GH_NAME}" yarn run publish-gh-pages

    - name: "website:preview"
      if: type = pull_request AND WEBSITE_CHANGED
      script:
        - yarn --cwd './website'
        - yarn --cwd './website' run build
        - npx surge --project ./website/build --domain wix-yoshi-${TRAVIS_PULL_REQUEST}.surge.sh
